FROM node:lts-alpine
WORKDIR /app

RUN mkdir -p /app/shared
RUN mkdir -p /app/scheduling-node-app

ADD lerna.json lerna.json
ADD package.json package.json
ADD scheduling-node-app/package.json scheduling-node-app/package.json
ADD shared/package.json shared/package.json

RUN npm install

ADD . /app
EXPOSE 8091

CMD ["yarn", "start:scheduling-node-app"]
